# @archeon {GLYPH_QUALIFIED_NAME}
# Generated by Archeon - Do not edit manually

from fastapi import APIRouter, HTTPException, Depends
from pydantic import BaseModel
{IMPORTS}

router = APIRouter(prefix="{ROUTE_PREFIX}", tags=["{TAG}"])


class {REQUEST_MODEL}(BaseModel):
{REQUEST_FIELDS}


class {RESPONSE_MODEL}(BaseModel):
{RESPONSE_FIELDS}


class {ERROR_MODEL}(BaseModel):
    detail: str
    code: str


@router.{METHOD}("{ROUTE}")
async def {HANDLER_NAME}(
{PARAMETERS}
) -> {RESPONSE_MODEL}:
    """
    {DOCSTRING}
    """
{HANDLER_BODY}
