// @archeon STO:themeStore
// Generated by Archeon - Pinia Theme Store
// Manages theme state (light/dark/system) AND color themes with persistence
//
// === THEME SYSTEM ARCHITECTURE ===
// This store manages TWO separate concerns:
// 1. MODE: Light/Dark/System - controls the brightness scheme
// 2. COLOR THEME: Project-specific color palettes that override --color-primary-* variables
//
// The color theme works by adding a CSS class to the document root.
// These classes override the --color-primary-* CSS variables.
// See: archeon/templates/_config/theme-presets.css for preset examples.
//
// Usage in components:
//   const { colorTheme, setColorTheme } = useThemeStore()
//   setColorTheme('purple') // Switches to purple theme
//
// The theme tokens propagate through:
//   design-tokens.json -> theme-presets.css -> STO:Theme -> CSS variables -> components
//
// === CUSTOMIZATION ===
// The COLOR_THEMES and COLOR_THEME_CLASSES below are EXAMPLES.
// Each project should define its own themes based on:
//   1. The color palettes in design-tokens.json
//   2. The theme classes in theme-presets.css
// Update these constants to match your project's design system.

import { defineStore } from 'pinia';
import { ref, computed, watch } from 'vue';

// Light/Dark mode constants (these are standard)
export const THEMES = {
  LIGHT: 'light',
  DARK: 'dark',
  SYSTEM: 'system',
};

// =============================================================================
// COLOR THEMES - CUSTOMIZE PER PROJECT
// =============================================================================
// These are example themes. Update to match your project's theme-presets.css.
// The keys become the values stored/used in code (e.g., 'blue', 'purple').
// Add/remove themes as needed for your design system.
export const COLOR_THEMES = {
  BLUE: 'blue',      // Example: maps to .theme-ocean
  PURPLE: 'purple',  // Example: maps to .theme-royal
  GREEN: 'green',    // Example: maps to .theme-forest
};

// Maps theme values to CSS class names from theme-presets.css
// Update this when you add/modify themes in theme-presets.css
const COLOR_THEME_CLASSES = {
  [COLOR_THEMES.BLUE]: 'theme-ocean',
  [COLOR_THEMES.PURPLE]: 'theme-royal',
  [COLOR_THEMES.GREEN]: 'theme-forest',
};
// =============================================================================

// Get system preference for light/dark
const getSystemTheme = () => {
  if (typeof window === 'undefined') return THEMES.LIGHT;
  return window.matchMedia('(prefers-color-scheme: dark)').matches 
    ? THEMES.DARK 
    : THEMES.LIGHT;
};

// Apply light/dark mode to DOM
const applyMode = (resolvedTheme) => {
  if (typeof document === 'undefined') return;
  
  const root = document.documentElement;
  root.classList.remove('light', 'dark');
  root.classList.add(resolvedTheme);
  root.style.colorScheme = resolvedTheme;
};

// Apply color theme to DOM (swaps --color-primary-* variables)
const applyColorTheme = (colorTheme) => {
  if (typeof document === 'undefined') return;
  
  const root = document.documentElement;
  // Remove all color theme classes
  Object.values(COLOR_THEME_CLASSES).forEach(cls => root.classList.remove(cls));
  // Add the selected theme class
  const themeClass = COLOR_THEME_CLASSES[colorTheme] || COLOR_THEME_CLASSES[COLOR_THEMES.BLUE];
  root.classList.add(themeClass);
};

// Load persisted mode preference
const loadPersistedTheme = () => {
  if (typeof localStorage === 'undefined') return THEMES.SYSTEM;
  return localStorage.getItem('archeon-theme') || THEMES.SYSTEM;
};

// Load persisted color theme
const loadPersistedColorTheme = () => {
  if (typeof localStorage === 'undefined') return COLOR_THEMES.BLUE;
  return localStorage.getItem('archeon-color-theme') || COLOR_THEMES.BLUE;
};

// Save mode to localStorage
const persistTheme = (theme) => {
  if (typeof localStorage === 'undefined') return;
  localStorage.setItem('archeon-theme', theme);
};

// Save color theme to localStorage
const persistColorTheme = (colorTheme) => {
  if (typeof localStorage === 'undefined') return;
  localStorage.setItem('archeon-color-theme', colorTheme);
};

export const useThemeStore = defineStore('theme', () => {
  // === State ===
  // Mode: light/dark/system
  const theme = ref(loadPersistedTheme());
  const resolvedTheme = ref(
    theme.value === THEMES.SYSTEM ? getSystemTheme() : theme.value
  );
  // Color theme: blue/purple/green
  const colorTheme = ref(loadPersistedColorTheme());

  // === Computed ===
  const isDark = computed(() => resolvedTheme.value === THEMES.DARK);
  const isLight = computed(() => resolvedTheme.value === THEMES.LIGHT);
  const isSystem = computed(() => theme.value === THEMES.SYSTEM);

  // === Actions: Light/Dark Mode ===
  function setTheme(newTheme) {
    theme.value = newTheme;
    resolvedTheme.value = newTheme === THEMES.SYSTEM ? getSystemTheme() : newTheme;
    persistTheme(newTheme);
    applyMode(resolvedTheme.value);
  }

  function toggleTheme() {
    const newTheme = resolvedTheme.value === THEMES.DARK ? THEMES.LIGHT : THEMES.DARK;
    setTheme(newTheme);
  }

  // === Actions: Color Theme ===
  function setColorTheme(newColorTheme) {
    colorTheme.value = newColorTheme;
    persistColorTheme(newColorTheme);
    applyColorTheme(newColorTheme);
  }

  function cycleColorTheme() {
    const themes = Object.values(COLOR_THEMES);
    const currentIndex = themes.indexOf(colorTheme.value);
    const nextIndex = (currentIndex + 1) % themes.length;
    setColorTheme(themes[nextIndex]);
  }

  // === Initialization ===
  function initTheme() {
    // Apply current mode (light/dark)
    applyMode(resolvedTheme.value);
    // Apply current color theme
    applyColorTheme(colorTheme.value);

    // Listen for system preference changes
    if (typeof window !== 'undefined') {
      const mediaQuery = window.matchMedia('(prefers-color-scheme: dark)');
      mediaQuery.addEventListener('change', (e) => {
        if (theme.value === THEMES.SYSTEM) {
          resolvedTheme.value = e.matches ? THEMES.DARK : THEMES.LIGHT;
          applyMode(resolvedTheme.value);
        }
      });
    }
  }

  // Watch for mode changes and apply
  watch(theme, (newTheme) => {
    resolvedTheme.value = newTheme === THEMES.SYSTEM ? getSystemTheme() : newTheme;
    applyMode(resolvedTheme.value);
  });

  return {
    // State
    theme,
    resolvedTheme,
    colorTheme,
    // Computed
    isDark,
    isLight,
    isSystem,
    // Actions: Mode
    setTheme,
    toggleTheme,
    // Actions: Color Theme
    setColorTheme,
    cycleColorTheme,
    // Init
    initTheme,
  };
});

export default useThemeStore;
