// @archeon STO:themeStore
// Generated by Archeon - Pinia Theme Store
// Manages theme state (light/dark/system) with persistence

import { defineStore } from 'pinia';
import { ref, computed, watch } from 'vue';

// Theme constants
export const THEMES = {
  LIGHT: 'light',
  DARK: 'dark',
  SYSTEM: 'system',
};

// Get system preference
const getSystemTheme = () => {
  if (typeof window === 'undefined') return THEMES.LIGHT;
  return window.matchMedia('(prefers-color-scheme: dark)').matches 
    ? THEMES.DARK 
    : THEMES.LIGHT;
};

// Apply theme to DOM
const applyTheme = (resolvedTheme) => {
  if (typeof document === 'undefined') return;
  
  const root = document.documentElement;
  root.classList.remove('light', 'dark');
  root.classList.add(resolvedTheme);
  root.style.colorScheme = resolvedTheme;
};

// Load persisted theme
const loadPersistedTheme = () => {
  if (typeof localStorage === 'undefined') return THEMES.SYSTEM;
  return localStorage.getItem('archeon-theme') || THEMES.SYSTEM;
};

// Save theme to localStorage
const persistTheme = (theme) => {
  if (typeof localStorage === 'undefined') return;
  localStorage.setItem('archeon-theme', theme);
};

export const useThemeStore = defineStore('theme', () => {
  // State
  const theme = ref(loadPersistedTheme());
  const resolvedTheme = ref(
    theme.value === THEMES.SYSTEM ? getSystemTheme() : theme.value
  );

  // Computed
  const isDark = computed(() => resolvedTheme.value === THEMES.DARK);
  const isLight = computed(() => resolvedTheme.value === THEMES.LIGHT);
  const isSystem = computed(() => theme.value === THEMES.SYSTEM);

  // Actions
  function setTheme(newTheme) {
    theme.value = newTheme;
    resolvedTheme.value = newTheme === THEMES.SYSTEM ? getSystemTheme() : newTheme;
    persistTheme(newTheme);
    applyTheme(resolvedTheme.value);
  }

  function toggleTheme() {
    const newTheme = resolvedTheme.value === THEMES.DARK ? THEMES.LIGHT : THEMES.DARK;
    setTheme(newTheme);
  }

  function initTheme() {
    // Apply current theme
    applyTheme(resolvedTheme.value);

    // Listen for system preference changes
    if (typeof window !== 'undefined') {
      const mediaQuery = window.matchMedia('(prefers-color-scheme: dark)');
      mediaQuery.addEventListener('change', (e) => {
        if (theme.value === THEMES.SYSTEM) {
          resolvedTheme.value = e.matches ? THEMES.DARK : THEMES.LIGHT;
          applyTheme(resolvedTheme.value);
        }
      });
    }
  }

  // Watch for theme changes and apply
  watch(theme, (newTheme) => {
    resolvedTheme.value = newTheme === THEMES.SYSTEM ? getSystemTheme() : newTheme;
    applyTheme(resolvedTheme.value);
  });

  return {
    // State
    theme,
    resolvedTheme,
    // Computed
    isDark,
    isLight,
    isSystem,
    // Actions
    setTheme,
    toggleTheme,
    initTheme,
  };
});

export default useThemeStore;
