// @archeon STO:themeStore
// Generated by Archeon - Zustand Theme Store
// Manages theme state (light/dark/system) with persistence

import { create } from 'zustand';
import { persist } from 'zustand/middleware';

// Theme type definitions
const THEMES = {
  LIGHT: 'light',
  DARK: 'dark',
  SYSTEM: 'system',
};

// Get system preference
const getSystemTheme = () => {
  if (typeof window === 'undefined') return THEMES.LIGHT;
  return window.matchMedia('(prefers-color-scheme: dark)').matches 
    ? THEMES.DARK 
    : THEMES.LIGHT;
};

// Apply theme to DOM
const applyTheme = (theme, resolvedTheme) => {
  if (typeof document === 'undefined') return;
  
  const root = document.documentElement;
  root.classList.remove('light', 'dark');
  root.classList.add(resolvedTheme);
  root.style.colorScheme = resolvedTheme;
};

// Create theme store with persistence
export const useThemeStore = create(
  persist(
    (set, get) => ({
      // State
      theme: THEMES.SYSTEM, // 'light' | 'dark' | 'system'
      resolvedTheme: getSystemTheme(), // Actual applied theme
      
      // Actions
      setTheme: (theme) => {
        const resolvedTheme = theme === THEMES.SYSTEM ? getSystemTheme() : theme;
        applyTheme(theme, resolvedTheme);
        set({ theme, resolvedTheme });
      },
      
      toggleTheme: () => {
        const { resolvedTheme } = get();
        const newTheme = resolvedTheme === THEMES.DARK ? THEMES.LIGHT : THEMES.DARK;
        applyTheme(newTheme, newTheme);
        set({ theme: newTheme, resolvedTheme: newTheme });
      },
      
      // Initialize theme (call on app mount)
      initTheme: () => {
        const { theme } = get();
        const resolvedTheme = theme === THEMES.SYSTEM ? getSystemTheme() : theme;
        applyTheme(theme, resolvedTheme);
        set({ resolvedTheme });
        
        // Listen for system preference changes
        if (typeof window !== 'undefined') {
          const mediaQuery = window.matchMedia('(prefers-color-scheme: dark)');
          mediaQuery.addEventListener('change', (e) => {
            const { theme } = get();
            if (theme === THEMES.SYSTEM) {
              const newResolvedTheme = e.matches ? THEMES.DARK : THEMES.LIGHT;
              applyTheme(theme, newResolvedTheme);
              set({ resolvedTheme: newResolvedTheme });
            }
          });
        }
      },
      
      // Computed-like getters
      isDark: () => get().resolvedTheme === THEMES.DARK,
      isLight: () => get().resolvedTheme === THEMES.LIGHT,
      isSystem: () => get().theme === THEMES.SYSTEM,
    }),
    {
      name: 'archeon-theme', // localStorage key
      partialize: (state) => ({ theme: state.theme }), // Only persist theme preference
    }
  )
);

// Export theme constants
export { THEMES };

// Convenience hook for React components
export const useTheme = () => {
  const store = useThemeStore();
  return {
    theme: store.theme,
    resolvedTheme: store.resolvedTheme,
    setTheme: store.setTheme,
    toggleTheme: store.toggleTheme,
    isDark: store.isDark(),
    isLight: store.isLight(),
    isSystem: store.isSystem(),
  };
};

export default useThemeStore;
