// @archeon {GLYPH_QUALIFIED_NAME}
// Generated by Archeon - Do not edit manually

import { create } from 'zustand';
import axios from 'axios';
{IMPORTS}

const initialState = {
{INITIAL_STATE}
};

export const use{STORE_NAME} = create((set, get) => ({
  ...initialState,

{ACTIONS}
}));

export default use{STORE_NAME};
