// @archeon {GLYPH_QUALIFIED_NAME}
// Generated by Archeon - Do not edit manually

import { create } from 'zustand';
{IMPORTS}

interface {STORE_NAME}State {
{STATE_INTERFACE}
}

interface {STORE_NAME}Actions {
{ACTIONS_INTERFACE}
}

type {STORE_NAME}Store = {STORE_NAME}State & {STORE_NAME}Actions;

const initialState: {STORE_NAME}State = {
{INITIAL_STATE}
};

export const use{STORE_NAME} = create<{STORE_NAME}Store>((set, get) => ({
  ...initialState,

{ACTIONS}
}));

export default use{STORE_NAME};
