"""
MongoDB database connection using Motor (async MongoDB driver).
Generated by Archeon.
"""
import os
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# MongoDB configuration
MONGODB_URI = os.getenv("MONGODB_URI", "mongodb://localhost:27017")
MONGODB_DB_NAME = os.getenv("MONGODB_DB_NAME", "app_db")

# Global database client
_client: AsyncIOMotorClient | None = None
_db = None


def get_client() -> AsyncIOMotorClient:
    """Get MongoDB client (singleton)."""
    global _client
    if _client is None:
        _client = AsyncIOMotorClient(MONGODB_URI)
    return _client


def get_database():
    """Get MongoDB database."""
    global _db
    if _db is None:
        _db = get_client()[MONGODB_DB_NAME]
    return _db


def get_collection(name: str):
    """Get a collection from the database."""
    return get_database()[name]


async def close_connection():
    """Close MongoDB connection."""
    global _client, _db
    if _client:
        _client.close()
        _client = None
        _db = None


# Convenience function for use in route dependencies
async def get_db():
    """Dependency for FastAPI routes."""
    return get_database()
