// @archeon {GLYPH_QUALIFIED_NAME}
// Generated by Archeon - Do not edit manually

{IMPORTS}

/**
 * {DOCSTRING}
 * 
{PARAMS_DOC}
 * @returns {RETURN_DOC}
 */
export function {FUNCTION_NAME}({PARAMETERS}): {RETURN_TYPE} {
{FUNCTION_BODY}
}

export default {FUNCTION_NAME};
