// @archeon {GLYPH_QUALIFIED_NAME}
// Generated by Archeon - Do not edit manually

import React{USE_STATE_IMPORT} from 'react';

{IMPORTS}

interface {COMPONENT_NAME}Props {
{PROPS_INTERFACE}
}

{STATE_INTERFACE}

export function {COMPONENT_NAME}({PROPS_DESTRUCTURE}: {COMPONENT_NAME}Props) {
{STATE_HOOKS}
{HANDLERS}
  return (
    <div data-testid="{COMPONENT_NAME_KEBAB}">
{RENDER_CONTENT}
    </div>
  );
}

export default {COMPONENT_NAME};
