// @archeon {GLYPH_QUALIFIED_NAME}
// Generated by Archeon - Do not edit manually

import React{USE_STATE_IMPORT} from 'react';

{IMPORTS}

export function {COMPONENT_NAME}({PROPS_DESTRUCTURE}) {
{STATE_HOOKS}
{HANDLERS}
  return (
    <div className="{TAILWIND_CLASSES}" data-testid="{COMPONENT_NAME_KEBAB}">
{RENDER_CONTENT}
    </div>
  );
}

export default {COMPONENT_NAME};
