<!-- @archeon {GLYPH_QUALIFIED_NAME} -->
<!-- Generated by Archeon - Do not edit manually -->

<script setup>
{IMPORTS}

defineProps({
{PROPS_DEFINITION}
});

{STATE_REFS}
{HANDLERS}
</script>

<template>
  <div data-testid="{COMPONENT_NAME_KEBAB}">
{RENDER_CONTENT}
  </div>
</template>

<style scoped>
{STYLES}
</style>
