<!-- @archeon {GLYPH_QUALIFIED_NAME} -->
<!-- Generated by Archeon - Do not edit manually -->

<script setup lang="ts">
{IMPORTS}

interface {COMPONENT_NAME}Props {
{PROPS_INTERFACE}
}

defineProps<{COMPONENT_NAME}Props>();

{STATE_REFS}
{HANDLERS}
</script>

<template>
  <div data-testid="{COMPONENT_NAME_KEBAB}">
{RENDER_CONTENT}
  </div>
</template>

<style scoped>
{STYLES}
</style>
