<!-- @archeon {GLYPH_QUALIFIED_NAME} -->
<!-- Generated by Archeon - Do not edit manually -->

<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue';
{STORE_IMPORT}
{IMPORTS}

// Props interface
interface Props {
{PROPS_INTERFACE}
}

// Emits interface
interface Emits {
{EMITS_INTERFACE}
}

const props = withDefaults(defineProps<Props>(), {
{PROPS_DEFAULTS}
});

const emit = defineEmits<Emits>();

{STATE_REFS}
{COMPUTED}
{HANDLERS}
{LIFECYCLE}
</script>

<template>
  <div 
    class="{COMPONENT_NAME_KEBAB}"
    data-testid="{COMPONENT_NAME_KEBAB}"
  >
{RENDER_CONTENT}
  </div>
</template>

<style scoped>
.{COMPONENT_NAME_KEBAB} {
  /* Component styles */
}
{STYLES}
</style>
