<!-- @archeon {GLYPH_QUALIFIED_NAME} -->
<!-- Generated by Archeon - Do not edit manually -->

<script setup>
import { ref, computed, onMounted, watch } from 'vue';
{STORE_IMPORT}
{IMPORTS}

const props = defineProps({
{PROPS_DEFINITION}
});

const emit = defineEmits({EMITS_DEFINITION});

{STATE_REFS}
{COMPUTED}
{HANDLERS}
{LIFECYCLE}
</script>

<template>
  <div 
    class="{TAILWIND_CLASSES}"
    data-testid="{COMPONENT_NAME_KEBAB}"
  >
{RENDER_CONTENT}
  </div>
</template>
