# @archeon {GLYPH_QUALIFIED_NAME}
# Generated by Archeon - Do not edit manually

from typing import Callable, Any
from dataclasses import dataclass, field
{IMPORTS}


@dataclass
class {EVENT_NAME}Event:
    """Event payload for {EVENT_NAME}."""
{EVENT_FIELDS}


class {EVENT_NAME}Emitter:
    """Event emitter for {EVENT_NAME}."""
    
    def __init__(self):
        self._listeners: list[Callable[[{EVENT_NAME}Event], None]] = []
    
    def subscribe(self, callback: Callable[[{EVENT_NAME}Event], None]) -> Callable[[], None]:
        """Subscribe to this event. Returns unsubscribe function."""
        self._listeners.append(callback)
        return lambda: self._listeners.remove(callback)
    
    def emit(self, event: {EVENT_NAME}Event) -> None:
        """Emit event to all listeners."""
        for listener in self._listeners:
            listener(event)
    
    def clear(self) -> None:
        """Remove all listeners."""
        self._listeners.clear()


# Singleton instance
{EVENT_NAME_LOWER}_emitter = {EVENT_NAME}Emitter()
