# @archeon {GLYPH_QUALIFIED_NAME}
# Generated by Archeon - Do not edit manually

from typing import Optional, Any
from pydantic import BaseModel, Field
from motor.motor_asyncio import AsyncIOMotorCollection
{IMPORTS}


class {MODEL_NAME}(BaseModel):
    """MongoDB document model for {ENTITY}."""
{SCHEMA_FIELDS}
    
    class Config:
        populate_by_name = True


class {MODEL_NAME}Repository:
    """Repository for {MODEL_NAME} operations."""
    
    def __init__(self, collection: AsyncIOMotorCollection):
        self.collection = collection

{METHODS}
